Cambalab/vue-admin

.npmignore
package.json
src/index.js

+ package.json information update
+ release and npm publish scripts
+ minor changes in index.js
Closes #21

21 update package json

---

src/components/Actions/List/List.vue
src/components/Admin/src/admin.vue
src/components/Core/src/core.vue
src/components/Resource/src/resource.vue
src/components/Ui/src/ui.vue
src/constants/ui.content.default.js
tests/e2e/specs/ui.spec.js

22 remove spanish comments in code

---

src/App.vue
utils/server-test/server.js
utils/server-test/services/articles.js
utils/server-test/services/magazines.js

+ A magazine resource for further testing
closes #40

40 implement a use case with more resources

---

src/components/Actions/List/List.vue

Fixes no dynamic resourceName bug

---

src/App.vue
vue.config.js

Adds some aliases in the webpack configuration

---

jest.config.js
package-lock.json
package.json
tests/unit/.eslintrc.js
tests/unit/resource.spec.js

+ Jest plugin to write unit tests

62 configure unit tests for vue components

---

jest.config.js
package.json
src/components/Resource/src/defaults.js
src/components/Resource/src/resource.vue
src/constants/error.messages.js
src/handlers/error/src/index.js
tests/unit/fixtures/resource/magazines.js
tests/unit/specs/resource.spec.js
vue.config.js

+ error handling for the resource component
+ default props module usage
+ unit tests for negative cases
Closes #67
Depends on #64

67 implement error handling for the resource component child of 64

---

jest.config.js
package.json
src/components/Resource/src/defaults.js
src/components/Resource/src/resource.vue
src/constants/error.messages.js
src/handlers/error/src/index.js
src/main.js
src/templates/src/en/error.json
src/templates/src/index.js
src/validators/src/components/resource.js
src/validators/src/index.js
tests/unit/specs/resource.spec.js
vue.config.js

+ validation handling
+ error messages templating
+ unit test for the Resource component redirect property (negative case)
+ Closes #68 
+ Depends on #67

68 implement properties validation for the error handler child of 67

---

utils/server-test/package-lock.json
utils/server-test/package.json
utils/server-test/server.js
utils/server-test/services/auth.js

+ Auth endpoint in the test server
+ Faker users
Closes #88

88 implement an auth service in the test server

---

package.json

+ Automatic changelog generation using the [github-changelog-generator](https://github.com/github-changelog-generator/github-changelog-generator) package.
closes #6

Updates package.json with a changelog script

---

utils/server-test/services/auth.js

Test serer: fixes lost users from the whitelist

---

Docs/Resource.md
README.md
demo/App.vue
demo/va-auth-adapter/axios.adapter.js
jest.config.js
src/router/route.bindings.js
src/router/route.hooks.js
src/va-auth/src/utils/index.js

+   Restrictions to routes by user permissions using vue-router beforeEnter hooks
+   Documentation updates
closes #96

96 integrate views permissions to the route hooks

---

src/index.js

Modifies index.js to expose components:
+ Views:
+   Create
+   Delete
+   Edit
+   EditButton
+   List
+   Show
+ AuthTypes
+ package.json:
+   name
+   description
closes #107

Updates index.js

---

.travis.yml
src/components/Wrappers/SimpleForm/SimpleFormWrapper.vue

20 - integrate travis ci dev

---

demo/App.vue
demo/components/authors/CreateAuthors.vue
demo/components/authors/EditAuthors.vue
demo/components/authors/ListAuthors.vue
demo/components/authors/ShowAuthors.vue
tests/e2e/factory/index.js
tests/e2e/factory/resources/authors.js
tests/e2e/factory/resources/index.js
tests/e2e/factory/store/initial.getters.js
tests/e2e/factory/store/initial.state.js
tests/e2e/factory/utils.js
tests/e2e/fixtures/authors.json
tests/e2e/specs/authors/create.spec.js
tests/e2e/specs/authors/edit.spec.js
tests/e2e/specs/authors/list.spec.js
tests/e2e/specs/authors/show.spec.js
utils/server-test/server.js
utils/server-test/services/authors.js
utils/server-test/utils/random-date-generator.js

Added authors mock service in server-test.
Added authors resource in vue-admin demo app.
Added e2e test for authors' new views.

79 improve demo app authors resource

---

src/index.js

Added missing Unauthorized component exposure in main index.js file.

Exposed Unauthorized component in index.js file.

---

demo/components/AuthCustomView.vue
src/components/Admin/src/Composer.vue

*    Vuetify support for `Admin` and all it's child components
*   Updates some colors in the `AuthCustomView` component
Closes #95

Composer: adds VApp as parent of Admin for Vuetify styles propagation

---

demo/components/articles/ListArticles.vue
src/components/Actions/Create/defaults.js
src/components/Actions/Edit/defaults.js
src/components/Actions/List/List.vue
src/components/Actions/List/defaults.js
src/components/Actions/Show/defaults.js
src/components/Actions/compose.js
tests/e2e/specs/articles/list.spec.js

-   Support for custom title in the `List` component.
Closes #4
-   [x] This change requires a documentation update
**Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce the cases. Please also list any relevant details for your test configuration**
-   [x] End to …

4 as a list action a default title should be used if none was provided

---

.github/PULL_REQUEST_TEMPLATE.md

Closes #163 
**Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration**
**1.** First merge this PR
**2.** Then create a MR
**Expected result:** the PR template should look like this one.
-   [x] **I have performed a self-review of my …

Adds a PULL REQUEST template

---

Docs/Admin/Admin.md
README.md

-   Improved documentation in the `README.md`
-   Updated documentation for `Admin.vue` in `Docs/Admin/Admin.md`
Closes #166 
-   [x] Documentation
-   [x] **I have performed a self-review of my own code**
-   [ ] I have commented my code, particularly in hard-to-understand areas
-   [x] I have made corresponding changes to the documentation
-   [x] **My changes generate no new warnings**
- …

166 readme update contributions sections and more

---

demo/components/articles/EditArticles.vue
src/components/Actions/Edit/Edit.vue
src/components/Actions/Edit/defaults.js
tests/e2e/specs/articles/edit.spec.js

*   custom title support for the `Edit` action.
*   e2e tests updated
Closes #2

2 as an edit actions a default title should be used

---

demo/components/articles/CreateArticles.vue
src/components/Actions/Create/Create.vue
src/components/Actions/Create/defaults.js
tests/e2e/specs/articles/create.spec.js

*   support to proie a custom title to create views
Closes #3

3 as a create action a default title should be used

---

demo/components/articles/ShowArticles.vue
src/components/Actions/Show/Show.vue
src/components/Actions/Show/defaults.js
tests/e2e/specs/articles/show.spec.js

*   support for custom `title` in the `Show` component.

172 as a show action a custom title can be provided

---

README.md

-   Credentials for the demo app in `README.md`
Closes #176
-   [ ] New feature (non-breaking change which adds functionality)
-   [x] Documentation update
**No code added**
- …

README.md: adds credentials information for the demo app

---

utils/server-test/package-lock.json
utils/server-test/package.json
utils/server-test/server.js
utils/server-test/services/articles.js
utils/server-test/services/auth.js
utils/server-test/services/authors.js
utils/server-test/services/magazines.js
utils/server-test/utils/random-date-generator.js

-   Server data generation using `fake-data-generator@0.1.10`
Closes #161
**Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce the cases. Please also list any relevant details for your test configuration**
-   [x] …

161 replace server author services specific data generators with fake data generator

---

.github/CODE_OF_CONDUCT.md

-   Code of Conduct adaptation from [**Contibution Covenant**](https://www.contributor-covenant.org/version/2/0/code_of_conduct)

Adds Contributor Covenant v2.0

---

src/components/Admin/src/Unauthenticated.vue
src/components/Layouts/src/AuthLayout/AuthLayout.vue
src/constants/ui.content.default.js
src/plugins/vuex/subscriptions.js
tests/unit/specs/admin/alerts.spec.js
tests/unit/specs/auth/auth.spec.js

-   AuthLayout snackbar integration with the Alerts system
Closes #198 
**Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce the cases. Please also list any relevant details for your test configuration**
-   [x] …

198 refactor the authlayout snackbar to use the alerts system

---

.github/CONTRIBUTING.md
.gitignore
.travis.yml
README.md
jest.config.js
package.json

-   Contribution guidelines document
-   Readme updates
-   Adds test coverage
Closes #202 
Closes #147 
-   [ ] New feature (non-breaking change which adds functionality)
-   [x] Documentation update
> The following options in **bold** are required for a PR approval. Please check the boxes only if necessary, it help us minimizing …

202 update contributing documentation

---

.travis.yml
README.md
jest.config.js
package-lock.json
package.json

-   Automatic unit test coverage generation using **codecov**
Closes #204 
**Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce the cases. Please also list any relevant details for your test configuration**
> The …

204 configure automatic test coverage report

---

package.json

-   Npm script update: ~prepublish~ -> **prepare**
Closes #28
Closes #185 
-   [x] **I have performed a …

Package.json: replaces prepublish script to prepare

---

src/components/Actions/Create/Create.vue
src/components/Actions/Edit/Edit.vue
src/components/Actions/List/List.vue
src/components/Actions/Show/Show.vue
src/components/UiComponents/Spinner/Spinner.vue
tests/unit/lib/utils/wrapper.js
tests/unit/specs/ui-components/spinner.spec.js

-   Tests for the Spinner component
Closes #216 
-   [ ] New feature (non-breaking change which adds functionality)
-   [x] Tests
-   [x] **I have performed a self-review of my …

216 implement unit tests for the spinner component

---

demo/App.vue
demo/components/magazines/ListMagazines.vue
src/components/Actions/List/List.vue
src/components/Actions/Show/Show.vue
src/components/UiComponents/DeleteButton/DeleteButton.vue
src/constants/ui.element.names.js
src/router/route.bindings.js
src/store/modules/crud.js
tests/unit/fixtures/actions/index.js
tests/unit/specs/ui-components/delete.button.spec.js

-   `DeleteButton` refactor: adds a `resoureIdName` prop
-   Implements unit tests
Closes #217
**Expected result:** a result description
> The following options in **bold** are required for a PR approval. Please check the boxes only if necessary, it help us …

217 implement unit tests for the delete button component

---

utils/server-test/package-lock.json

Reverts Cambalab/vue-admin#233

Revert "Bump ini from 1.3.5 to 1.3.8 in /utils/server-test"
